### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by e042** [Qveshn/LightAPI#27]
Hi,
since I'm planning to program a plugin that needs the api functions, I wanted to ask how much LightAPI affects the performance.
Can you give me a rough guideline how many lights I can create without the server starting to lag?
Thanks in advance!

**Comment by Qveshn** [comment]
Hi
Could you tell me what kind of plugin are you planning? What for lights will be created? And how often are you going to destroy/create lights?

**Comment by e042** [comment]
I am planning a plugin that will allow builders to place light sources from a server.

**Comment by Qveshn** [comment]
permanently?

**Comment by Qveshn** [comment]
This plugin was not designed for permanent light sources. Instead of this plugin, I propose to consider the capabilities of another VarLight plugin. It not only exposes the lights in the world, but saves them in a separate world map (files are like mca)

There are some limitations with creating lights in LightAPI plugin. This plugin only sets the light at the position of the block, but does not store information about the light source. Thus, standard minecraft mechanics can destroy the generated light during the update of the blocks. For example, if you put any block next to it, then the light in the adjacent block will be recalculated and the light will be destroyed, because there is no information that there was a light source in it. 
Such loss of light must be checked separately from time to time and, if destroyed, re-created.
It's like putting an opened iron trapdoor somewhere, which will remain open until another block is placed next to it. After that, the neighboring blocks will be updated and the trapdoor will be closed.

There is also a problem when placing lights next to each other. In order for the light to spread over 15 blocks around, the plugin triggers the internal mechanics of minecraft to recount the six side blocks, which will cause the destruction of the light installed in them. In other words, the plugin does not allow the lights to be placed next to each other.

**Comment by Qveshn** [comment]
For example, I can bring a code that allows you to expose the light in the desired block.

```
import ru.beykerykt.lightapi.LightType;
import ru.beykerykt.lightapi.LightAPI;
...
void setLight(Location location, int lightLevel, LightType lightType) {
    Block block = location.getBlock();
    int oldLightLevel = lightType == LightType.BLOCK ? block.getLightFromBlocks() : block.getLightFromSky();
    if (oldLightLevel != lightLevel) {
        if (lightLevel > 0) {
            LightAPI.createLight(location, lightType, lightLevel, false);
        } else {
            LightAPI.deleteLight(location, lightType, false);
        }
        for (ChunkInfo chunkInfo : LightAPI.collectChunks(location, lightType, Math.max(lightLevel, oldLightLevel))) {
            LightAPI.updateChunk(chunkInfo, lightType);
        }
    }
}
```

You can experiment with this code. Put the light somewhere and then check how it disappears if you put another block next to it.

**Comment by e042** [comment]
@Qveshn Thanks for your quick reply and for pointing out VarLight, I'll suggest that to the server team.
