### ISSUE TITLE
No LightAPI implementations was found for Paper v1_17_R1

### ISSUE THREAD

**Issue by OpticFusion1** [Qveshn/LightAPI#38]
Would it be possible to implement support for Paper?

**Comment by Qveshn** [comment]
What LightAPI version do you use and what exact message do you see in console?
And does Paper uses StarLight engine?

**Comment by OpticFusion1** [comment]
LightAPI 3.5.2
StarLight: Depends on if a non-modified paper server runs with it or not

**Comment by Qveshn** [comment]
Hm... intersting...
LightAPI 3.5.2 should support paper 1.17.1 if paper based on craftbukkit and without StarLight.
Can you give me the exact way/url to download the same paper version that you got? (+ version/build number itself )
Also give me the exact message in console where you see  "no LifgtAPI  implementations" or like this.

Upd:
I download paper 1.17.1 build 241 here:
But it contains Starlight. Therefore LightAPI is incompatible wit this one.
Where can I get non-modified paper server 1.17.1 without Starlight?

**Comment by OpticFusion1** [comment]
Hmm, I downloaded the most recent. So chances are it has Starlight in it as well.

**Comment by Qveshn** [comment]
You can check Starlight presence if open jar-file as archive (zip) and search files with names like "*starlight*"
There path in jar-file "/ca/spottedleaf/starlight/..." also indicates about presence of Starlight

**Comment by Qveshn** [comment]
Discord:

https://discord.com/channels/538139695079489581/802420410377437195/865178654781472798
>Euan — 15.07.2021
hey @Spottedleaf wanted to CC you in this, https://github.com/Qveshn/LightAPI/issues/32, you might be able to give more details then me
...
trying to get this plugin to work with starlight

https://discord.com/channels/538139695079489581/802420410377437195/865178889293529098
>Spottedleaf — 15.07.2021
as of 1.17 I don't support custom light sources, as mojang has a custom light block

https://discord.com/channels/538139695079489581/802420410377437195/865605283089612810
>serjproch — 16.07.2021 **IT'S ME**
Hi @Spottedleaf 
The problem is that LIGHT BLOCK does not cover all the functionality of setting the light, as it was implemented in the vanilla version of the light engine:
>
>1. LIGHT BLOCK can be set only in the air (it is an independent block) while custom lights could be placed inside other blocks. This allows other blocks to simulate light emission as well.
>
>2. LIGHT BLOCK can emmit light only of LightType.BLOCK, while cutom lights can be set both for BLOCK and SKY types. This allows for natural light from the sky (e.g. inside late dark canyons).
>
>3. LIGHT BLOCK can be set only from min to max world height, while custom light can be set also in one section below and above world. This allows to illuminate structures from the outside of the world. 
>
>I am maintaining a LightAPI plugin. This plugin is used by other third party plugins as an API for the ability to set custom lights.
It turned out that servers based on Starlight have a rewritten light engine and LightAPI is not compatible with such servers.
It expected the presence of objects of classes LightEngineBlock and LightEngineSky inherited from LightEngineLayer, through which the plugin sets lights and recalculates its propagation to adjacent blocks.
>
>It would be nice to have this possibility also in Starlight as well, as it will significantly expand the functionality of the LIGHT BLOCK.
It is not necessary to reproduce imitation of all classes and methods from vanilla mechanics. A variant of the interface that differs from the vanilla server is possible. If this is possible, an implementation for servers with built-in Starlight will be added to the LightAPI plugin.
And everyone will be happy.
>
>Thanks
😃 

No reaction on my post. Spottedleaf did not answer
😟

**Comment by OpticFusion1** [comment]
That's disappointing honestly. Oh well, If anyone complains I'll just tell them to either complain to the paper devs or switch back to spigot lol

**Comment by Qveshn** [comment]
@OpticFusion1 Starlight was included in paper since build 232. Therefore you can use build 231 and LightAPI will work 😄
